/*
 * This source file was generated by the Gradle 'init' task
 */
package mockito_advanced;

import static org.mockito.Mockito.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ServiceTest {
    @Test
    public void testServiceWithMockRepository() {
        // 1. Create mock repository
        Repository mockRepository = mock(Repository.class);
        
        // 2. Stub the repository method
        when(mockRepository.getData()).thenReturn("Mock Data");

        // 3. Test the service
        Service service = new Service(mockRepository);
        String result = service.processData();

        assertEquals("Processed Mock Data", result);
        
        // Verify the mock was called
        verify(mockRepository).getData();
    }
}