/*
 * This source file was generated by the Gradle 'init' task
 */
package mockito;

public interface ExternalApi {
    String getData();
    String fetchById(int id);
    void log(String message);
}
